import { createClient } from '../supabase/client';
import { Database } from '../database.types';

/**
 * Service for interacting with database tables
 */
export class DataService {
  private supabase = createClient();

  /**
   * Get all items from a table with pagination and sorting
   */
  async getAll(
    tableName: string, 
    options: { 
      page?: number, 
      pageSize?: number, 
      sortField?: string, 
      sortDirection?: 'asc' | 'desc',
      skipSorting?: boolean,
      query?: string
    } = {}
  ) {
    // Default configuration values
    const defaultSortField = 'id';
    const defaultSortDirection = 'asc';
    
    const {
      page = 1,
      pageSize = 10,
      sortField = defaultSortField,
      sortDirection = defaultSortDirection,
      skipSorting = false,
      query
    } = options;

    // Calculate range for pagination
    const from = (page - 1) * pageSize;
    const to = from + pageSize - 1;
    
    // Build query
    let queryBuilder = this.supabase
      .from(tableName as keyof Database['public']['Tables'])
      .select('*', { count: 'exact' });
    
    // Apply custom query if provided
    if (query) {
      queryBuilder = queryBuilder.or(query);
    }
    
    // Apply sorting unless explicitly skipped
    // This is useful for junction tables that might not have an id column
    if (!skipSorting) {
      queryBuilder = queryBuilder.order(sortField, { ascending: sortDirection === 'asc' });
    }
    
    // Execute query with pagination
    const { data, error, count } = await queryBuilder.range(from, to);
    
    if (error) {
      console.error('Error fetching items:', error);
      throw error;
    }
    
    return {
      data,
      pagination: {
        page,
        pageSize,
        total: count || 0,
        totalPages: count ? Math.ceil(count / pageSize) : 0
      }
    };
  }

  /**
   * Get a single item by ID
   */  
  async getById(tableName: string, id: number | string) {
    const { data, error } = await this.supabase
      .from(tableName as keyof Database['public']['Tables'])
      .select('*')
      .eq('id', id)
      .single();

    if (error) {
      console.error('Error fetching item:', error);
      throw error;
    }

    return data;
  }

  /**
   * Create a new item
   */
  async create(tableName: string, item: Record<string, unknown>) {
    // Remove id field if present as it's auto-generated by the database
    // Extract and ignore id field if present as it's auto-generated
    const { id: _id, ...itemWithoutId } = item; // eslint-disable-line @typescript-eslint/no-unused-vars
    
    const { data, error } = await this.supabase
      .from(tableName as keyof Database['public']['Tables'])
      .insert(itemWithoutId)
      .select();

    if (error) {
      console.error('Error creating item:', error);
      throw error;
    }

    return data[0];
  }

  /**
   * Update an existing item
   */
  async update(tableName: string, id: number | string, item: Record<string, unknown>) {
    // Remove id field if present as we're already specifying it in the query
    const { id: _id, ...itemWithoutId } = item; // eslint-disable-line @typescript-eslint/no-unused-vars
    
    const { data, error } = await this.supabase
      .from(tableName as keyof Database['public']['Tables'])
      .update(itemWithoutId)
      .eq('id', id)
      .select();

    if (error) {
      console.error('Error updating item:', error);
      throw error;
    }

    return data[0];
  }

  /**
   * Delete an item
   */
  async delete(tableName: string, id: number | string) {
    const { error } = await this.supabase
      .from(tableName as keyof Database['public']['Tables'])
      .delete()
      .eq('id', id);

    if (error) {
      console.error('Error deleting item:', error);
      throw error;
    }

    return true;
  }
  
  /**
   * Search for items in a table using case-insensitive pattern matching
   * @param tableName The name of the table to search in
   * @param field The field to search in
   * @param query The search query
   * @param select Fields to select (default: '*')
   */
  async search(
    tableName: string,
    field: string,
    query: string,
    select: string = '*'
  ) {
    // Add wildcards to the query for partial matching
    const searchPattern = `%${query}%`;
    
    // Execute the search query using ilike for case-insensitive pattern matching
    const { data, error } = await this.supabase
      .from(tableName as keyof Database['public']['Tables'])
      .select(select)
      .ilike(field, searchPattern);
      
    if (error) {
      console.error('Error searching items:', error);
      throw error;
    }

    return data;
  }
  
  /**
   * Get many-to-many relationships
   * @param junctionTable The junction table connecting the two entities
   * @param foreignKey The foreign key in the junction table referencing the parent
   * @param parentId The ID of the parent item
   * @param relatedKey The foreign key in the junction table referencing the related item
   * @param options Optional pagination options
   */
  async getManyToManyRelationships(
    junctionTable: string,
    foreignKey: string,
    parentId: number | string,
    relatedKey: string,
    options: { 
      page?: number, 
      pageSize?: number
    } = {}
  ) {
    const {
      page = 1,
      pageSize = 50  // Default to a larger page size for relationships
    } = options;

    // Calculate range for pagination
    const from = (page - 1) * pageSize;
    const to = from + pageSize - 1;
    
    // Build query to get junction records
    // We don't sort here since junction tables might not have standard id columns
    const query = this.supabase
      .from(junctionTable as keyof Database['public']['Tables'])
      .select(`*, ${relatedKey}(*)`, { count: 'exact' })
      .eq(foreignKey, parentId);
    
    // Execute query with pagination
    const { data, error, count } = await query.range(from, to);
    
    if (error) {
      console.error(`Error fetching many-to-many relationships from ${junctionTable}:`, error);
      throw error;
    }
    
    return {
      data,
      pagination: {
        page,
        pageSize,
        total: count || 0,
        totalPages: count ? Math.ceil(count / pageSize) : 0
      }
    };
  }

  /**
   * Delete records by a custom query
   * @param tableName The table to delete from
   * @param foreignKey The foreign key field to filter on
   * @param foreignValue The value of the foreign key to match
   * @param relatedKey Optional related key field for additional filtering
   * @param relatedValue Optional value of the related key to match
   */
  async deleteByQuery(
    tableName: string, 
    foreignKey: string, 
    foreignValue: string | number,
    relatedKey?: string,
    relatedValue?: string | number
  ) {
    let query = this.supabase
      .from(tableName as keyof Database['public']['Tables'])
      .delete()
      .eq(foreignKey, foreignValue);
      
    // Add additional filter if related key and value are provided
    if (relatedKey && relatedValue !== undefined) {
      query = query.eq(relatedKey, relatedValue);
    }

    const { error } = await query;

    if (error) {
      console.error('Error deleting items by query:', error);
      throw error;
    }

    return true;
  }

  /**
   * Get related items for a one-to-many relationship
   * @param relatedTable The table containing the related items (the "many" side)
   * @param foreignKey The foreign key field in the related table that references the parent
   * @param parentId The ID of the parent item
   * @param options Optional pagination and sorting options
   */
  async getRelatedItems(
    relatedTable: string,
    foreignKey: string,
    parentId: number | string,
    options: { 
      page?: number, 
      pageSize?: number, 
      sortField?: string, 
      sortDirection?: 'asc' | 'desc'
    } = {}
  ) {
    // Default configuration values
    const defaultSortField = 'id';
    const defaultSortDirection = 'asc';
    
    const {
      page = 1,
      pageSize = 50,  // Default to a larger page size for related items
      sortField = defaultSortField,
      sortDirection = defaultSortDirection
    } = options;

    // Calculate range for pagination
    const from = (page - 1) * pageSize;
    const to = from + pageSize - 1;
    
    // Build query to get related items
    let query = this.supabase
      .from(relatedTable as keyof Database['public']['Tables'])
      .select('*', { count: 'exact' })
      .eq(foreignKey, parentId);
    
    // Apply sorting
    query = query.order(sortField, { ascending: sortDirection === 'asc' });
    
    // Execute query with pagination
    const { data, error, count } = await query.range(from, to);
    
    if (error) {
      console.error(`Error fetching related items from ${relatedTable}:`, error);
      throw error;
    }
    
    return {
      data,
      pagination: {
        page,
        pageSize,
        total: count || 0,
        totalPages: count ? Math.ceil(count / pageSize) : 0
      }
    };
  }
}

// Export a singleton instance
export const dataService = new DataService();
